version: "3"

services:
  application:
    image: spring-boot-docker-compose  
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net
    depends_on:
      - oracledb
  

  oracledb:
    image: gvenzl/oracle-xe:21-slim  
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=0614  
      - ORACLE_DATABASE=xe
    networks:
      - springboot-db-net
    shm_size: 1gb 
    volumes:
      - /data/oracle

networks:
  springboot-db-net: