version: "3.8"

services:
  application:
    image: spring-boot-docker-compose  # Make sure this image is built or exists
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net
    depends_on:
      - oracledb
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracledb:1521/XE
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: 0614

  oracledb:
    image: gvenzl/oracle-xe:21-slim
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 0614   
    shm_size: 1g
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - springboot-db-net

volumes:
  oracle-data:

networks:
  springboot-db-net:
